import type { Profile } from "@/lib/types";

const chromosomes = [
  { id: "1", snps: 59028 },
  { id: "2", snps: 57409 },
  { id: "3", snps: 46978 },
  { id: "4", snps: 40274 },
  { id: "5", snps: 41901 },
  { id: "6", snps: 47934 },
  { id: "7", snps: 37905 },
  { id: "8", snps: 36849 },
  { id: "9", snps: 32647 },
  { id: "10", snps: 38888 },
  { id: "11", snps: 36468 },
  { id: "12", snps: 35381 },
  { id: "13", snps: 27724 },
  { id: "14", snps: 23227 },
  { id: "15", snps: 21536 },
  { id: "16", snps: 22670 },
  { id: "17", snps: 20160 },
  { id: "18", snps: 21632 },
  { id: "19", snps: 14987 },
  { id: "20", snps: 18327 },
  { id: "21", snps: 10184 },
  { id: "22", snps: 10431 },
  { id: "X", snps: 17909 },
];

export const helle: Profile = {
  slug: "helle",
  firstName: "Helle",
  status: "published",
  tested: "FamilyTreeDNA · myOrigins v3 · mtFull Sequence",
  tagline: "North, inland, and Ireland",
  lede: "A genome split three ways across Western Europe — Scandinavia, the Central European plain, and a clear Irish current — with a Nordic maternal twig from the tenth century.",
  heroImage: "/images/helle-hero.jpg",
  heroAlt: "Atlantic cliffs on the west coast of Ireland at dusk",
  heroStats: [
    { label: "Scandinavia", value: "41%", color: "aurora" },
    { label: "Central Europe", value: "41%", color: "amber" },
    { label: "Ireland", value: "19%", color: "ink" },
  ],
  originsHeadline: {
    lead: "Still all Europe.",
    accent: "But three voices, not one.",
  },
  originsLede:
    "FamilyTreeDNA myOrigins v3 paints Helle as entirely European, then splits her almost evenly between Scandinavia and Central Europe, with a substantial Irish third. Click a slice.",
  origins: [
    {
      id: "scandinavia",
      label: "Scandinavia",
      percent: 41,
      color: "#7ec8a3",
      image: "/images/scandinavia.jpg",
      kicker: "The northern current",
      summary:
        "Forty-one percent of Helle’s autosomal ancestry matches Scandinavian references — Denmark, Sweden, Norway, and the wider Nordic peninsula.",
      detail:
        "This is the same North Sea world as other kits in this archive, but it is not the whole story. For Helle it is one of two equal pillars, not a seventy-percent majority.",
    },
    {
      id: "central-europe",
      label: "Central Europe",
      percent: 41,
      color: "#d4a054",
      image: "/images/central-europe.jpg",
      kicker: "The inland river",
      summary:
        "Another forty-one percent points to Central Europe — Germany, the Alps, the Danube basin, and the older farming heart of the continent.",
      detail:
        "Tied with Scandinavia. Helle’s genome is a hinge between the Nordic world and the Central European plain, a balance Pernille’s kit does not show.",
    },
    {
      id: "ireland",
      label: "Ireland",
      percent: 19,
      color: "#6f9b78",
      image: "/images/ireland.jpg",
      kicker: "The western door",
      summary:
        "Nineteen percent matches Irish references. That is not a trace. It is a third voice, loud enough to be a chapter.",
      detail:
        "Nineteen percent is grandparent-scale if you take the number as a person — or a western British-Isles cluster that FamilyTreeDNA labelled Ireland. Their own method paper says splitting Ireland from Great Britain reduces accuracy for both. Pernille inherited none of it, which fits a few long blocks that her father did not pass, not a Viking-Age sprinkle. Still an estimate, not a parish.",
    },
  ],
  ancientHeadline: {
    lead: "Almost half forager.",
    mid: "Then the fields.",
    end: "A lighter steppe.",
  },
  ancientLede:
    "Helle’s ancient European recipe is close to the northern pattern: a large hunter-gatherer layer, a strong farming stream, and a smaller Bronze Age pulse from the steppe.",
  ancientOrigins: [
    {
      id: "hunter",
      label: "Hunter-Gatherer",
      percent: 49,
      color: "#c45c6a",
      image: "/images/hunter-gatherer.jpg",
      emblem: "/images/emblem-hunter.jpg",
      era: "Pleistocene → Mesolithic",
      when: "From ~45,000 years ago",
      summary:
        "Forty-nine percent of Helle’s European autosomal ancestry still resembles the first modern humans who walked into a thawing continent.",
      detail:
        "After the last ice, hunter-gatherer bands lived from La Brana in Spain to Loschbour in Luxembourg and Motala in Sweden. In Helle that older forager layer is the largest ancient component FamilyTreeDNA reports — just shy of half.",
    },
    {
      id: "farmer",
      label: "Early Farmer",
      percent: 40,
      color: "#7ec8a3",
      image: "/images/farmer.jpg",
      emblem: "/images/emblem-farmer.jpg",
      era: "Neolithic",
      when: "~8,000–7,000 years ago",
      summary:
        "Wheat, pottery, and settled valleys. Farmers moved from the Near East along Anatolia into the Danube and on toward the Atlantic.",
      detail:
        "Forty percent of Helle’s ancient European ancestry tracks that farming expansion — Linear Pottery, Funnelbeaker, and the long walk of fields toward Ireland’s west.",
    },
    {
      id: "invader",
      label: "Metal Age Invader",
      percent: 11,
      color: "#d4a054",
      image: "/images/yamnaya.jpg",
      emblem: "/images/emblem-invader.jpg",
      era: "Bronze Age",
      when: "~5,800 years ago",
      summary:
        "A smaller pulse from the Pontic–Caspian steppe: horses, wagons, and bronze.",
      detail:
        "Yamnaya-related herders moved west in the Bronze Age. FamilyTreeDNA folds that stream into “Metal Age Invader.” In Helle it is 11% — present, not dominant.",
    },
  ],
  haplogroup: {
    id: "H1e1b1f1",
    parent: "H1e1b1f",
    pathLabel: "H → H1 → H1e → H1e1 → H1e1b → H1e1b1 → H1e1b1f → H1e1b1f1",
    formed: "branched from H1e1b1f around 1700 BCE",
    headline: "A Nordic motherline from around 950 CE.",
    tmrca: {
      meanLabel: "950 CE",
      ci95: "717–1176 CE",
    },
    testers: {
      total: 15,
      known: "Denmark 6, Norway 2, Sweden 1",
    },
    rarityNote:
      "Fifteen testers currently share H1e1b1f1. The named origins are Denmark, Norway, and Sweden — a Scandinavian twig, broader than Pernille’s rarer H10a1u.",
  },
  haploPath: [
    {
      haplogroup: "H1e1b1f1",
      yearLabel: "950 CE",
      year: 950,
      era: "Middle Ages",
      place: "Scandinavia",
      copy: "Helle’s own maternal haplogroup. The parent H1e1b1f is Bronze Age (FamilyTreeDNA mean 1700 BCE). The most recent woman shared by the fifteen living testers likely lived around 950 CE (95% 717–1176). Six name Denmark, two Norway, one Sweden. That is a Viking-Age twig on a much older Central European family.",
    },
    {
      haplogroup: "H1e1b1f",
      yearLabel: "1700 BCE",
      year: -1700,
      era: "Metal Ages",
      place: "Europe",
      copy: "The parent branch formed in the Bronze Age. FamilyTreeDNA estimates H1e1b1f around 1700 BCE (95% interval roughly 2455–1022 BCE).",
    },
    {
      haplogroup: "H1e1b1",
      yearLabel: "3350 BCE",
      year: -3350,
      era: "Stone Age / Metal Ages",
      place: "Europe",
      copy: "A Late Neolithic node. Many of Helle’s closer ancient matches sit under H1e1b1, around 3350 BCE.",
    },
    {
      haplogroup: "H1e1",
      yearLabel: "3750 BCE",
      year: -3750,
      era: "Stone Age / Metal Ages",
      place: "Europe",
      copy: "H1e1 is a well-travelled European maternal family. FamilyTreeDNA still files Beethoven here; hair sequenced in 2023 is H1b1, so the real shared node with the composer is H1.",
    },
    {
      haplogroup: "H1",
      yearLabel: "5200 BCE",
      year: -5200,
      era: "Stone Age",
      place: "Europe",
      copy: "H1 is one of the great European daughters of H, expanding with post-glacial and Neolithic Europe.",
    },
    {
      haplogroup: "H",
      yearLabel: "8000 BCE",
      year: -8000,
      era: "Stone Age",
      place: "Near East & Caucasus",
      copy: "Haplogroup H formed outside Europe, in the northern Near East and southern Caucasus, then spread west. About four in ten European maternal lines are H today.",
    },
    {
      haplogroup: "HV",
      yearLabel: "10,000 BCE",
      year: -10000,
      era: "Stone Age",
      place: "West Asia",
      copy: "HV is the parent of H and V. The ice is retreating. People are still few.",
    },
    {
      haplogroup: "R0",
      yearLabel: "37,000 BCE",
      year: -37000,
      era: "Upper Paleolithic",
      place: "West Eurasia",
      copy: "R0 sits deep under the later European and Near Eastern maternal tree.",
    },
    {
      haplogroup: "N",
      yearLabel: "57,000 BCE",
      year: -57000,
      era: "Out of Africa",
      place: "Near East",
      copy: "N is the Eurasian sister of M. After the walk out of Africa, N’s descendants peopled the north and west.",
    },
    {
      haplogroup: "L3",
      yearLabel: "64,000 BCE",
      year: -64000,
      era: "Out of Africa",
      place: "East Africa",
      copy: "L3 is the African mother of all non-African maternal lines.",
    },
    {
      haplogroup: "L (mt-Eve)",
      yearLabel: "141,000 BCE",
      year: -141000,
      era: "Stone Age",
      place: "East Africa",
      copy: "Mitochondrial Eve is not the first woman. She is the most recent woman from whom every living person inherits a maternal line.",
    },
    {
      haplogroup: "L'AAAB",
      yearLabel: "725,000 BCE",
      year: -725000,
      era: "Denisovan split",
      place: "Deep time",
      copy: "The oldest rung on this chart. Every modern human shares it.",
    },
  ],
  motherlineMapCaption:
    "A schematic walk: East Africa → Near East → haplogroup H → H1e1b1f1 in Scandinavia.",
  motherlineSpotlights: [
    {
      img: "/images/emblem-maternal.jpg",
      title: "A Nordic twig",
      copy: "Fifteen testers share H1e1b1f1. Named origins: Denmark, Norway, and Sweden. Broader than some rarer H10 twigs, still a small family.",
    },
    {
      img: "/images/caucasus.jpg",
      title: "Through H1",
      copy: "H1 expands across post-glacial Europe. Helle’s line is a late, northern leaf on that large tree.",
    },
    {
      img: "/images/scandinavia.jpg",
      title: "Home water",
      copy: "The living geography of this haplogroup is Scandinavian. The autosomal Irish chapter sits beside it, not inside the mitochondria.",
    },
  ],
  connectionsLede:
    "FamilyTreeDNA lists notable and archaeological people who share a maternal ancestor with Helle. These are not cousins in any family sense. Living match names are not shown here.",
  connections: [
    {
      id: "beethoven",
      name: "Ludwig van Beethoven",
      dates: "1770–1827 CE",
      kind: "notable",
      rarity: "rare",
      shared: "H1",
      sharedYear: "5200 BCE",
      place: "Bonn / Vienna",
      image: "/images/central-europe.jpg",
      blurb:
        "FamilyTreeDNA still lists Beethoven at H1e1. Authentic hair sequenced in 2023 (Begg et al.) is H1b1+16362C. Helle meets that line at H1, around 5200 BCE — a fun fact one step higher than the Discover page says, still not a family portrait.",
    },
    {
      id: "sweyn",
      name: "Sweyn II of Denmark",
      dates: "1019–1076 CE",
      kind: "notable",
      rarity: "rare",
      shared: "H",
      sharedYear: "8000 BCE",
      place: "Denmark",
      image: "/images/viking-langeland.jpg",
      blurb:
        "The last Viking king of Denmark. The shared node is haplogroup H, thousands of years before either of them.",
    },
    {
      id: "birger",
      name: "Birger Jarl",
      dates: "1210–1266 CE",
      kind: "notable",
      rarity: "rare",
      shared: "H",
      sharedYear: "8000 BCE",
      place: "Sweden",
      image: "/images/sweden-winter.jpg",
      blurb:
        "The jarl who helped found Stockholm. Again the shared ancestor is H, in the Stone Age.",
    },
    {
      id: "agnes",
      name: "Agnes of Waiblingen",
      dates: "1072–1143 CE",
      kind: "notable",
      rarity: "rare",
      shared: "R0",
      sharedYear: "37,000 BCE",
      place: "Germany",
      image: "/images/central-europe.jpg",
      blurb:
        "A hinge between Salian, Hohenstaufen, and Babenberg houses. The shared ancestor here is far older: R0.",
    },
    {
      id: "slonk",
      name: "Slonk Hill man",
      dates: "391–203 BCE",
      kind: "ancient",
      rarity: "rare",
      shared: "H",
      sharedYear: "8000 BCE",
      place: "Brighton, England",
      image: "/images/british-isles.jpg",
      blurb:
        "Late Iron Age Britain. A young man associated with Iron Age Britain, meeting Helle’s line at haplogroup H.",
    },
    {
      id: "avar",
      name: "Goldenen Stiege Avars",
      dates: "600–800 CE",
      kind: "ancient",
      rarity: "rare",
      shared: "H1e1b1",
      sharedYear: "3350 BCE",
      place: "Lower Austria",
      image: "/images/central-europe.jpg",
      blurb:
        "Several Late Avar burials at Mödling sit on Helle’s closer H1e1b1 node — a Carpathian-basin chapter of the same motherline (Wang et al. 2025).",
    },
    {
      id: "stambolovo",
      name: "Stambolovo 15848",
      dates: "1100–700 BCE",
      kind: "ancient",
      rarity: "rare",
      shared: "H1e1b1",
      sharedYear: "3350 BCE",
      place: "Haskovo, Bulgaria",
      image: "/images/bronze-plain.jpg",
      blurb:
        "An Early Iron Age woman at Stambolovo (I15848, Lazaridis et al. 2022). Her own twig is H1e1b1j. About one in 2,100 customers sit this close. A Balkan Iron Age sister of the family that later names H1e1b1f1.",
    },
    {
      id: "brucken",
      name: "Brücken 34",
      dates: "436–542 CE",
      kind: "ancient",
      rarity: "rare",
      shared: "H1e1b1",
      sharedYear: "3350 BCE",
      place: "Saxony-Anhalt, Germany",
      image: "/images/bronze-plain.jpg",
      blurb:
        "An ~11-year-old girl of the Thuringian world (Gretzinger et al. 2025). Same H1e1b1 node as the Avars and the Bulgarian Iron Age woman — Central Europe still holding the motherline in the migration period.",
    },
    {
      id: "neanderthal",
      name: "Neanderthal",
      dates: "~40,000 years ago",
      kind: "deep",
      rarity: "common",
      shared: "L'AA",
      sharedYear: "379,000 BCE",
      place: "Eurasia",
      image: "/images/hunter-gatherer.jpg",
      blurb:
        "Every living person shares this node. A cousin on a far older maternal fork, not a private family secret.",
    },
    {
      id: "sima",
      name: "Sima de los Huesos",
      dates: "600,000–180,000 BCE",
      kind: "deep",
      rarity: "common",
      shared: "L'AAAB",
      sharedYear: "725,000 BCE",
      place: "Atapuerca, Spain",
      image: "/images/caucasus.jpg",
      blurb:
        "The Pit of Bones. Oldest sequenced hominin DNA. A shared human depth, not a personal relic.",
    },
  ],
  chromosomes,
  genome: {
    snps: chromosomes.reduce((sum, c) => sum + c.snps, 0),
    build: "Build 37 autosomal export",
    painting:
      "Chromosome painting at continent scale is Western European, with Scandinavian, Central European, and Irish components rather than a single bloc.",
  },
  kinship: {
    otherSlug: "pernille",
    otherName: "Pernille",
    role: "paternal granddaughter",
    href: "/shared",
  },
};
